version: "3.4"

services:
  mongo-container:
    image: mongo:latest
    container_name: cqrs-mongodb
    restart: always
    network_mode: techbankNet
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/data/db"
volumes:
  mongodb_data:
    driver: local